import type { PersonalWishes } from "../schema/wishes.ts";

/**
 * Converts the current PersonalWishes state into a formatted Markdown document,
 * explicitly appending the required fictional disclaimer as specified in the brief.
 */
export function generateMarkdown(wishes: PersonalWishes): string {
  const generatedDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let childrenSection = "_Waiting for input..._";
  if (wishes.has_children === false) {
    childrenSection = "No living children declared (explicitly confirmed).";
  } else if (wishes.children && wishes.children.length > 0) {
    childrenSection = wishes.children.map((c, i) => `${i + 1}. **${c.name}**`).join("\n");
  } else if (wishes.has_children === true && (!wishes.children || wishes.children.length === 0)) {
    childrenSection = "Children declared, names pending specification.";
  }

  const executorSection =
    wishes.executor
      ? `- **Name:** ${wishes.executor.name}\n- **Relationship to User:** ${wishes.executor.relationship}`
      : "_Waiting for input..._";

  const giftsSection =
    wishes.specific_gifts && wishes.specific_gifts.length > 0
      ? wishes.specific_gifts.map((g, i) => `${i + 1}. ${g}`).join("\n")
      : wishes.specific_gifts === null
      ? "_Waiting for input..._"
      : "_None specified_";

  let worldwideCoverageStr = "_Waiting for input..._";
  if (wishes.covers_worldwide_assets === true) {
    worldwideCoverageStr = "Yes: Covers worldwide assets across all jurisdictions.";
  } else if (wishes.covers_worldwide_assets === false) {
    worldwideCoverageStr = "No: Strictly limited to domestic/local assets.";
  }

  return `# PERSONAL WISHES DOCUMENT (DRAFT)

> **FICTIONAL DOCUMENT NOTICE:** This is a fictional Personal Wishes Document generated by **Document Intake Assistant** for demonstration and preliminary intake purposes only. This document does **NOT** constitute legal advice, a binding legal will, or a solicitor-client relationship.

---

**Generated Date:** ${generatedDate}  
**Document Status:** ${wishes.full_name ? "Draft Prepared" : "Incomplete Draft"}  
**Intake Standard:** Wenup LLM Document Intake Assistant Specification

---

## 1. Testator Identification
- **Full Name:** ${wishes.full_name ?? "_Waiting for input..._"}
- **Home Address:** ${wishes.home_address ?? "_Waiting for input..._"}

---

## 2. Territorial Asset Scope
- **Covers Worldwide Assets:** ${worldwideCoverageStr}

---

## 3. Children and Descendants
- **Has Children:** ${wishes.has_children === null ? "_Waiting for input..._" : wishes.has_children ? "Yes" : "No"}
${childrenSection}

---

## 4. Personal Representative / Executor
${executorSection}

---

## 5. Specific Gifts and Bequests
${giftsSection}

---

## 6. Additional Wishes
${wishes.additional_wishes ? wishes.additional_wishes : "_Waiting for input..._"}

---

## Statutory Execution Notice
*This is a fictional draft document. In order to create a legally binding Last Will and Testament, formal statutory execution requirements (such as signing in the physical presence of two independent adult witnesses who sign in attestation) must be observed in accordance with the governing probate laws of your domicile.*
`;
}

/**
 * Triggers a browser file download for the generated Markdown document.
 */
export function downloadMarkdownFile(wishes: PersonalWishes, filename?: string): void {
  const content = generateMarkdown(wishes);
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  
  const sanitizedName = wishes.full_name
    ? wishes.full_name.toLowerCase().replace(/[^a-z0-9]+/g, "-")
    : "personal-wishes";
  const finalFilename = filename || `${sanitizedName}-draft.md`;

  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", finalFilename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
